### ISSUE TITLE
validation fails when `block-list` input is `undefined`

### ISSUE THREAD

**Issue by Borda** [redhat-plumbers-in-action/advanced-issue-labeler#218]
### Type of issue

Bug Report

### Description

We would like to use this feature, but somehow we are not able to make it run even if we simply follow the example in the readme, the integration https://github.com/Lightning-AI/lightning/pull/17484 and the error:

```
with:
    issue-form: {
    "bug_description": "test",
    "versions": "ver: 1.6.x",
    "how_to_reproduce_the_bug": "",
    "error_messages_and_logs": "```\r\n# Error messages and logs here please\r\n```",
    "environment": "<details>\r\n  <summary>Current environment</summary>\n\n```\r\n#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):\r\n#- PyTorch Lightning Version (e.g., 1.5.0):\r\n#- Lightning App Version (e.g., 0.5.2):\r\n#- PyTorch Version (e.g., 2.0):\r\n#- Python version (e.g., [3](https://github.com/Lightning-AI/lightning/actions/runs/4822458653/jobs/8589717538#step:4:3).[9](https://github.com/Lightning-AI/lightning/actions/runs/4822458653/jobs/8589717538#step:4:9)):\r\n#- OS (e.g., Linux):\r\n#- CUDA/cuDNN version:\r\n#- GPU models and configuration:\r\n#- How you installed Lightning(`conda`, `pip`, source):\r\n#- Running environment of LightningApp (e.g. local, cloud):\r\n```\n\n</details>",
    "more_info": ""
  }
    section: versions
    token: ***
Error: , versions, undefined | , versions, undefined
Error: undefined, undefined,  | , versions, undefined
Error: An instance of Labeler has failed the validation:
 - property _inputs._blockList has failed the following constraints: minLength
```

The failing run is https://github.com/Lightning-AI/lightning/actions/runs/4822458653/jobs/8589717538

Also, it is confusing as the step is :green_circle: even if it fails inside

**Comment by Borda** [comment]
seems that the issue comes with `multiple: true`

**Comment by jamacku** [comment]
Hi,
Thank you for reporting this issue. I'm sorry `advanced-issue-labeler` doesn't work for you on the first try.

I did some debugging on my fork -  https://github.com/jamacku/lightning/issues

> `Error: An instance of Labeler has failed the validation:`
> `  - property _inputs._blockList has failed the following constraints: minLength`

It seems that the validation of the `block-list` input is incorrect. Your issue can be workaround by setting `block-list` input to some value

```yml
- name: Set labels based on severity field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: versions
          block-list: |  # <-- this value needs to be set (workaround)
            None
          token: ${{ secrets.GITHUB_TOKEN }}
```

> `Error: , versions, undefined | , versions, undefined`
> `Error: undefined, undefined,  | , versions, undefined`

The rest of the errors can be ignored, I plan to use a new validation library that should be more flexible and reliable than the current one.

> UPDATE: with multiple also `.` is problematic character

The character `.` should not be an issue. The only unsupported character is `,`.

I'm sorry that you have encountered these issues, I'll try to fix them ASAP and improve logging.

**Comment by Borda** [comment]
I was playing with `block-list` inside the `advanced-issue-labeler.yml` so it did not fail but also did not add any labels...
see my debugging in https://github.com/Borda/lightning/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc before I'll nude this working fork

**Comment by jamacku** [comment]
I have tried the following setup:

`1_bug_report.yaml`

```yml
- type: dropdown
    id: versions
    attributes:
      label: What version are you seeing the problem on?
      description: select all version where you have experienced this issue
      multiple: true
      options:
        - "v1.6.x"
        - "v1.7.x"
        - "v1.8.x"
        - "v1.9.x"
        - "v2.0.x"
        - "master"
    validations:
      required: true
```

`advanced-issue-labeler.yml`
```yml
policy:
  - section:
    - id: ['versions']
      block-list: []
      label:
        - name: "ver: 1.6.x"
          keys: ['v1.6.x']
        - name: "ver: 1.7.x"
          keys: ['v1.7.x']
        - name: "ver: 1.8.x"
          keys: ['v1.8.x']
        - name: "ver: 1.9.x"
          keys: ['v1.9.x']
        - name: "ver: 2.0.x"
          keys: ['v2.0.x']
        - name: "ver: 2.1.x"
          keys: ['master']
```

`labeler-issue.yml`

```yml
name: Label Issues
on:
  issues:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  label-component:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      issues: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/1_bug_report.yaml

      - name: Set labels based on severity field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: versions
          token: ${{ secrets.GITHUB_TOKEN }}
```

- https://github.com/jamacku/lightning/issues/5

It labeled issues correctly. In the `advanced-issue-labeler.yml` config file, the property `block-list` is required. It would make sense to make it optional, but for now, it is required. You have to use `block-list: []`
