### ISSUE TITLE
Is it possible to store the output of the policy for later step in the workflow?

### ISSUE THREAD

**Issue by ACyphus** [redhat-plumbers-in-action/advanced-issue-labeler#297]
@jamacku 👋 Thanks for working on this action—it's been incredibly helpful!

I'm curious if it's possible to access the result of the policy in a later workflow step? As well as applying a label, I'm trying to add a step to my workflow that also updates a GitHub project field, but I can't seem to access the results of the policy.

Any suggestions? Or is this not possible?

**Comment by jamacku** [comment]
I am glad to hear that you found this GHA helpful.

This is not possible so far, but it should be possible to add/implement it. I would like to know more details about what output you would like to see. Also, some examples would be great.

Internally: The policy will define the labels that will be set at the end.
Q: Would it be enough for your use case to have access to the list of the labels that will be set via output?

There is also a plan to add support for discussion forms, but I haven't yet time to implement it:
- https://github.com/redhat-plumbers-in-action/advanced-issue-labeler/issues/197

**Comment by ACyphus** [comment]
So my use case is that I'm taking an issue form field input:

```yml
- type: dropdown
    id: team
    attributes:
      label: What does the security concern impact?
      description: What is at risk due to the concern?
      options:
        - Acme the company Acme company/employee data or Acme infrastructure
        - Acme products services or Acme customers
        - Unknown
    validations:
      required: false
```

I'm then using this action 💖 to convert that into more useful data:

```yml
- template: ['security-report.yml']
    section:
      - id: ['team']
        block-list: []
        label:
          - name: 'THOR IR'
            keys: ['Acme the company Acme company/employee data or Acme infrastructure']
          - name: 'PSIRT'
            keys: ['Acme products services or Acme customers']
          - name: 'PSIRT'
            keys: ['Unknown']
```

And setting a label on the issue 🎉 

However, I also need to set a field called `Team` for this issue on a project. I can use something like https://github.com/github/update-project-action but I need to pass it a value to set for that project field. With `stefanbuck/github-issue-parser` I can access the outputs to use one as a value: https://github.com/stefanbuck/github-issue-parser?tab=readme-ov-file#action-outputs

This doesn't get me the data friendly output from the policy though! 😅 

---

> Q: Would it be enough for your use case to have access to the list of the labels that will be set via output?

Yes! If I were able to access a list of labels, or a specific label by a key that would be wonderful. 

For example with the above policy and this action step:

```yml
- name: Set labels for security reports
  id: set-labels
  uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
  with:
    issue-form: ${{ steps.issue-parser.outputs.jsonString }}
    template: 'security-report.yml'
    token: ${{ secrets.GITHUB_TOKEN }}
```

I'd love to be able to access a specific label with the policy id as the key `${{ steps.set-labels.outputs.labels.team }}`

Or a list of labels with `${{ steps.set-labels.outputs.labels}}`
